
import React, { useState } from 'react';
import { BookOpen, ArrowRight, Plus, Trash2, X } from 'lucide-react';
import { EditableText, EditableImage } from '../components/Editable';
import { useContent } from '../services/contentContext';
import { UI_LABELS } from '../constants';
import { Article } from '../types';

export const Knowledge: React.FC = () => {
  const { language, articles, isAdmin, addArticle, updateArticle, deleteArticle } = useContent() as any; // Cast to any to access new methods
  const suffix = language === 'en' ? '_en' : '';
  const labels = UI_LABELS[language];
  const [selectedArticle, setSelectedArticle] = useState<Article | null>(null);

  const handleAddArticle = async () => {
    // Generate a temporary ID or let DB handle it? 
    // We'll let DB handle it, but for optimistic UI we might need to wait.
    // Or we send a partial object.
    const newArticle = {
      // id: generated by DB
      image: 'https://picsum.photos/600/400?random=' + Date.now(),
      title: 'หัวข้อบทความใหม่ (Edit Me)',
      title_en: 'New Article Title (Edit Me)',
      excerpt: 'เนื้อหาโดยย่อ... (Edit Me)',
      excerpt_en: 'Short excerpt... (Edit Me)',
      details: 'เนื้อหารายละเอียดทั้งหมด เขียนได้ยาวเท่าที่ต้องการ... (Click to Edit)',
      details_en: 'Full content details here... (Click to Edit)'
    };
    await addArticle(newArticle);
  };

  const handleRemoveArticle = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (confirm("Delete this article?")) {
      await deleteArticle(id);
      if (selectedArticle?.id === id) setSelectedArticle(null);
    }
  };

  const updateArticleField = async (id: string, field: keyof Article, value: string) => {
    const articleToUpdate = articles.find((a: Article) => a.id === id);
    if (articleToUpdate) {
      const updated = { ...articleToUpdate, [field]: value };
      await updateArticle(updated);
      
      // Update modal if open
      if (selectedArticle?.id === id) {
        setSelectedArticle(updated);
      }
    }
  };

  return (
    <div className="py-12 bg-brand-dark min-h-screen">
      <div className="container mx-auto px-4">
        <h1 className="text-4xl font-bold text-center mb-4 text-brand-lime">{labels.knowledge}</h1>
        <p className="text-center text-gray-400 mb-12">{language === 'th' ? 'บทความและสาระน่ารู้เกี่ยวกับการจัดกิจกรรม' : 'Articles and interesting facts about event organization.'}</p>

        {/* Admin Add Button */}
        {isAdmin && (
          <div className="text-center mb-12">
            <button 
              onClick={handleAddArticle}
              className="bg-brand-lime text-black px-8 py-3 rounded-full font-bold hover:bg-white hover:scale-105 transition flex items-center gap-2 mx-auto shadow-lg shadow-lime-500/20"
            >
              <Plus size={24} /> {language === 'th' ? 'เพิ่มบทความใหม่' : 'Add New Article'}
            </button>
            <p className="text-gray-500 text-sm mt-2">{language === 'th' ? 'กดปุ่มนี้เพื่อเพิ่มการ์ดบทความ แล้วแก้ไขข้อความ/รูปภาพในการ์ด' : 'Click to add an article card, then edit text/image directly.'}</p>
          </div>
        )}

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {articles.map((article: Article) => (
            <div key={article.id} className="bg-brand-light rounded-xl overflow-hidden shadow-md hover:shadow-lime-500/20 transition flex flex-col border border-gray-700 group relative">
              <div className="h-48 relative">
                 <EditableImage 
                    id={`img_blog_${article.id}`} 
                    overrideSrc={article.image}
                    alt="Blog" 
                    onSave={(newSrc) => updateArticleField(article.id, 'image', newSrc)}
                    className="w-full h-full object-cover group-hover:scale-105 transition duration-500"
                  />
                  {/* Remove Button for Admin */}
                  {isAdmin && (
                    <button 
                      onClick={(e) => handleRemoveArticle(article.id, e)}
                      className="absolute top-2 right-2 bg-red-600 text-white p-2 rounded-full shadow-lg hover:bg-red-700 z-10 opacity-0 group-hover:opacity-100 transition"
                    >
                      <Trash2 size={16} />
                    </button>
                  )}
              </div>
              <div className="p-6 flex-grow flex flex-col">
                <div className="flex items-center text-xs text-brand-orange font-bold mb-2 gap-1">
                  <BookOpen size={14} />
                  <span>ARTICLE</span>
                </div>
                
                {/* Dynamic Title */}
                <EditableText 
                  id={`blog_title_${article.id}${suffix}`}
                  tag="h3"
                  overrideValue={language === 'en' ? (article.title_en || article.title) : article.title}
                  onSave={(val) => updateArticleField(article.id, language === 'en' ? 'title_en' : 'title', val)}
                  className="text-xl font-bold mb-3 text-white min-h-[1.5em]"
                />

                {/* Dynamic Excerpt */}
                <EditableText 
                  id={`blog_excerpt_${article.id}${suffix}`}
                  tag="p"
                  multiline
                  overrideValue={language === 'en' ? (article.excerpt_en || article.excerpt) : article.excerpt}
                  onSave={(val) => updateArticleField(article.id, language === 'en' ? 'excerpt_en' : 'excerpt', val)}
                  className="text-gray-400 text-sm mb-4 flex-grow min-h-[3em]"
                />

                <button 
                  onClick={() => setSelectedArticle(article)}
                  className="text-brand-lime font-bold flex items-center gap-1 hover:gap-2 transition-all self-start hover:text-white mt-auto"
                >
                  {labels.read_more} <ArrowRight size={16} />
                </button>
              </div>
            </div>
          ))}

          {/* Empty State */}
          {articles.length === 0 && (
            <div className="col-span-full text-center py-20 text-gray-500 border-2 border-dashed border-gray-800 rounded-xl">
              <p>{language === 'th' ? 'ยังไม่มีบทความ' : 'No articles found.'}</p>
            </div>
          )}
        </div>
      </div>

      {/* Article Detail Modal */}
      {selectedArticle && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/90 backdrop-blur-sm" onClick={() => setSelectedArticle(null)}>
          <div 
            className="bg-brand-light rounded-2xl max-w-4xl w-full max-h-[90vh] overflow-y-auto relative border border-gray-700 shadow-2xl flex flex-col"
            onClick={e => e.stopPropagation()}
          >
            {/* Close Button */}
            <button 
              onClick={() => setSelectedArticle(null)}
              className="absolute top-4 right-4 bg-black/50 text-white p-2 rounded-full hover:bg-red-500 transition z-20"
            >
              <X size={24} />
            </button>
            
            {/* Image Header */}
            <div className="h-[250px] md:h-[400px] w-full shrink-0 relative">
               <img src={selectedArticle.image} alt="Cover" className="w-full h-full object-cover" />
               <div className="absolute inset-0 bg-gradient-to-t from-brand-light to-transparent"></div>
            </div>
            
            {/* Content Body */}
            <div className="p-8 md:p-12 -mt-12 relative z-10">
               <span className="bg-brand-orange text-black font-bold px-3 py-1 rounded text-xs uppercase tracking-wider mb-4 inline-block shadow">
                 Knowlege & Tips
               </span>
               
               <h2 className="text-3xl md:text-4xl font-bold text-white mb-8 leading-tight">
                 {language === 'en' ? (selectedArticle.title_en || selectedArticle.title) : selectedArticle.title}
               </h2>

               <div className="prose prose-invert prose-lg max-w-none text-gray-300">
                 {/* Editable Full Details */}
                 <EditableText 
                    id={`blog_details_${selectedArticle.id}${suffix}`}
                    tag="div"
                    multiline
                    overrideValue={
                      language === 'en' 
                      ? (selectedArticle.details_en || selectedArticle.details || "No details available.") 
                      : (selectedArticle.details || "ไม่มีรายละเอียด")
                    }
                    onSave={(val) => updateArticleField(selectedArticle.id, language === 'en' ? 'details_en' : 'details', val)}
                    className="whitespace-pre-wrap min-h-[200px]"
                 />
               </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
